/* Auto-generated by genmsg_cpp for file /home/jianlan/gps_tt4/gps_tt4/src/gps_agent_pkg/msg/SUPERballState.msg */
#ifndef GPS_AGENT_PKG_MESSAGE_SUPERBALLSTATE_H
#define GPS_AGENT_PKG_MESSAGE_SUPERBALLSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Point.h"
#include "geometry_msgs/Point.h"
#include "std_msgs/Float64.h"
#include "std_msgs/Float64.h"

namespace gps_agent_pkg
{
template <class ContainerAllocator>
struct SUPERballState_ {
  typedef SUPERballState_<ContainerAllocator> Type;

  SUPERballState_()
  : pos1()
  , pos2()
  , motor_pos1()
  , motor_pos2()
  {
  }

  SUPERballState_(const ContainerAllocator& _alloc)
  : pos1(_alloc)
  , pos2(_alloc)
  , motor_pos1(_alloc)
  , motor_pos2(_alloc)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos1_type;
   ::geometry_msgs::Point_<ContainerAllocator>  pos1;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos2_type;
   ::geometry_msgs::Point_<ContainerAllocator>  pos2;

  typedef  ::std_msgs::Float64_<ContainerAllocator>  _motor_pos1_type;
   ::std_msgs::Float64_<ContainerAllocator>  motor_pos1;

  typedef  ::std_msgs::Float64_<ContainerAllocator>  _motor_pos2_type;
   ::std_msgs::Float64_<ContainerAllocator>  motor_pos2;


  typedef boost::shared_ptr< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_agent_pkg::SUPERballState_<ContainerAllocator>  const> ConstPtr;
}; // struct SUPERballState
typedef  ::gps_agent_pkg::SUPERballState_<std::allocator<void> > SUPERballState;

typedef boost::shared_ptr< ::gps_agent_pkg::SUPERballState> SUPERballStatePtr;
typedef boost::shared_ptr< ::gps_agent_pkg::SUPERballState const> SUPERballStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gps_agent_pkg::SUPERballState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gps_agent_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gps_agent_pkg::SUPERballState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff612ff5e9d1aa9e5d77318fb84086de";
  }

  static const char* value(const  ::gps_agent_pkg::SUPERballState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff612ff5e9d1aa9eULL;
  static const uint64_t static_value2 = 0x5d77318fb84086deULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gps_agent_pkg/SUPERballState";
  }

  static const char* value(const  ::gps_agent_pkg::SUPERballState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Point pos1\n\
geometry_msgs/Point pos2\n\
std_msgs/Float64 motor_pos1\n\
std_msgs/Float64 motor_pos2\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const  ::gps_agent_pkg::SUPERballState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pos1);
    stream.next(m.pos2);
    stream.next(m.motor_pos1);
    stream.next(m.motor_pos2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SUPERballState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_agent_pkg::SUPERballState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gps_agent_pkg::SUPERballState_<ContainerAllocator> & v) 
  {
    s << indent << "pos1: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos1);
    s << indent << "pos2: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos2);
    s << indent << "motor_pos1: ";
s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.motor_pos1);
    s << indent << "motor_pos2: ";
s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.motor_pos2);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GPS_AGENT_PKG_MESSAGE_SUPERBALLSTATE_H

